# Cloudflare Pages configuration for Parker Duck game
name = "duck-nukem"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "dist"

# Pages build output directory
pages_build_output_dir = "dist"

[[build.environment_variables]]
NODE_ENV = "production"

# Optional: Custom headers for game assets
[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]  
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]  
Cache-Control = "public, max-age=31536000, immutable" 